### ISSUE TITLE
examples/server.rs doesn't work !

### ISSUE THREAD

**Issue by OzqurYalcin** [hyperium/h2#469]
```
[dependencies]
env_logger = { version = "0.7" }
h2 = { version = "0.2" }
http = { version = "0.2" }
hyper = { version = "0.13" }
bytes = { version = "0.5" }
tokio = { version = "0.2", features = ["full"] }
```

`rustc version : 1.43.1`

When I run examples/server.rs code with the above dependencies without any changes on example,
after request localhost:5928 it prints 
`  -> err=Error { kind: Proto(PROTOCOL_ERROR) }`

**Comment by seanmonstar** [comment]
That is saying that a request was bad. How do you connect to the server?

**Comment by OzqurYalcin** [comment]
> That is saying that a request was bad. How do you connect to the server?

client: google chrome / os: windows

I think h2 doesn't work without tls. Is it ?
If so, it would be great if you add an example of how to use it with tls.

**Comment by seanmonstar** [comment]
HTTP/2 *can* work without TLS, using what is called "prior knowledge". Browsers usually don't know, so they assume HTTP/1 unless TLS can be used with ALPN to pick h2.

If you want to test the server, you can use the client example. The repo doesn't include TLS since the exact TLS library you pick is up to you.

I'm going to close this since the server example does work.

**Comment by ouvaa** [comment]
@seanmonstar can you pls provide an example of implementing tls on the library? i'm new to rust
