### ISSUE TITLE
Release plan for support on tokio v0.3?

### ISSUE THREAD

**Issue by LEXUGE** [hyperium/h2#499]
I see tokio v0.3 is supported on git version, however, there seems like no plan date available to release, which makes some downstream crates hard to update (https://github.com/bluejekyll/trust-dns/pull/1262#issue-509465856).

Do we have a date on release? Or can we have an alpha version being released early?

**Comment by bluejekyll** [comment]
I'd like to suggest that perhaps the hesitance on releasing `h2` in the face of possibly needing other breaking changes for `hyper` or other downstream dependencies, is probably being a little overly conservative. This library is generally not a user facing library. Most folks will be building with other libraries as the primary usage of this, giving it a bit of an air-gap from breaking changes effecting a significant number of projects, see [reverse_dependencies](https://crates.io/crates/h2/reverse_dependencies).

I don't want to speak for others, but I think it would be a small amount of work to update any of those libraries even if a `0.4` needs to be released due to issues integrating with `hyper` or other downstream libraries.

**Comment by taiki-e** [comment]
I think we can close as #504 merged.
