### ISSUE TITLE
Ignore 1xx frames

### ISSUE THREAD

**Issue by inikulin** [hyperium/h2#515]
Currently when hyper encounters such frames it resets the stream with an error. The plan for now is to just ignore these informational frames. With the next step being an implementation of API to handle them in h2 and hyper (tracked in #167).

**Comment by inikulin** [comment]
@seanmonstar any pointers for where to start in the code? Also, do you have any ideas how we can test it, considering that we don't have a server capable of sending such frames yet?

**Comment by seanmonstar** [comment]
You'd probably be able to add a check before calling [recv.recv_headers](https://github.com/hyperium/h2/blob/978c71270a952b43fc0004ae6363932bb15f11c5/src/proto/streams/streams.rs#L206), where if the `Peer` is client, and there is a 1xx `status`, the headers frame could be ignored instead of triggering the stream to enter the streaming state.

Or possibly it should happen *inside* `recv.recv_headers`, before calling `open`, I haven't though about which makes more sense.

For tests, you can add to `tests/h2-tests/tests/client_request.rs`. In there you can see it's possible to make a mock server with a recipe of h2 frames that would be received and sent, so you can send a headers from with 103, and then a headers frame with 200. It may be worth adding tests for a few combination of behaviors that could happen (you decide).
