### ISSUE TITLE
Unexpected GOAWAY on small message

### ISSUE THREAD

**Issue by l-monninger** [hyperium/h2#802]
# Summary
See https://github.com/hyperium/tonic/issues/1992#issue-2582126786

**Comment by seanmonstar** [comment]
It really would be helpful to see a description inline here, instead of following a series of links. But, one thing I notice: it's a GOAWAY from the `Library`, which means it is an error case that the library detected and triggered, as opposed to being received from the peer. For example, if you have a client, and the server sent back a frame that is bigger than the default max size, that could trigger it. (If that's the case, the peer is being especially bad, since the max frame size cannot be assumed, it is negotiated.)

**Comment by l-monninger** [comment]
Hey, this ended up being an issue with our ALB configuration. Closing.
